version: '3.8'
services:

    afs:
      container_name: afs
      image: fargeo/afs
      build:
        context: ..
        dockerfile: afs/Dockerfile
      command: run_arches
      volumes:
        - ../arches/:/web_root/arches
        - ./:/web_root/afs
        - cantaloupe-data:/web_root/afs/afs/uploadedfiles
      env_file:
        - ./docker/env_file.env
      ports:
        - 8001:8000
      # depends_on:
      #   - db_afs
      #   - elasticsearch_afs
      #   - couchdb_afs
      stdin_open: true
      tty: true

    # afs_livereload:
    #   profiles:
    #     - livereload
    #   container_name: afs_livereload
    #   image: fargeo/afs
    #   build:
    #     context: ..
    #     dockerfile: afs/Dockerfile
    #   command: run_livereload
    #   volumes:
    #     - ../arches/:/web_root/arches
    #     - ./:/web_root/afs
    #     - cantaloupe-data:/web_root/afs/afs/uploadedfiles
    #   env_file:
    #     - ./docker/env_file.env
    #   ports:
    #     - 35729:35729      
    #   depends_on:
    #       - afs
    #   stdin_open: true
    #   tty: true


    # for documentation on using the uclalibrary cantaloupe image:        
    # https://gitlab.com/ucla-library/docker-cantaloupe/-/blob/master/configs/cantaloupe.properties.default-dev
    cantaloupe_afs:
      container_name: cantaloupe_afs
      image: uclalibrary/cantaloupe:5.0.3-0
      volumes:
        - cantaloupe-data:/imageroot
      ports:
        - 8183:8182
      env_file:
        - ./docker/env_file.env

networks:
  default:
    external: true
    name: arches_dev

volumes:
    arches-log:
    arches-static:
    cantaloupe-data:
